### ISSUE TITLE
函数里分配了内存，但是没有释放的指令

### ISSUE THREAD

**Issue by iBigDane** [jubgjf/bmp-decoder#1]
我把你的库移植到ESP32上，反复读取图片的时候发现会导致ESP32重启，因为你库里的结构体内存是动态分配的，但是又没有释放指令，建议把结构体改为静态的内存吧。这个库帮了我很大忙，注释恰到好处，我用它在ESP32上实现了bmp图片的显示，示例也有如何读取指定像素的示例，这个其他库里都不好找，谢谢。是否有时间也写一个16位bmp的解析库。

**Comment by jubgjf** [comment]
感谢您使用这个仓库。这个仓库其实是我学C语言用来练手的，无论是代码风格/技巧/内存安全等方面都比较差。感谢您指出内存释放这个问题，我会找时间改正。但是由于我对BMP格式并不是很了解，16位BMP的解码可能不会实现。

**Comment by jubgjf** [comment]
临时修复见：f2e7e1b3df82667be4d5d971cacb7fd66bc16db3
